### ISSUE TITLE
"version `GLIBCXX_3.4.29' not found" when running apt-get, gcc:9 and gcc:10 amd64 container images

### ISSUE THREAD

**Issue by Amitie10g** [docker-library/gcc#98] opened 2023-06-23 13:38 UTC
When building a custom image using the gcc:9 and gcc:10 base images, I got error when running apt/apt-get:

```
apt-get: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libapt-private.so.0.0)
apt-get: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libapt-pkg.so.6.0)
```

Returning 1, leading unable to continue.

Using `ldd`, got the following information:
```
$ ldd /usr/bin/apt-get
/usr/bin/apt-get: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libapt-private.so.0.0)
/usr/bin/apt-get: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libapt-pkg.so.6.0)
        linux-vdso.so.1 (0x00007ffc7a089000)
        libapt-private.so.0.0 => /lib/x86_64-linux-gnu/libapt-private.so.0.0 (0x00007fee1b22f000)
        libapt-pkg.so.6.0 => /lib/x86_64-linux-gnu/libapt-pkg.so.6.0 (0x00007fee1b034000)
        libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00007fee1ae5f000)
        libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007fee1ae45000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fee1ac64000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fee1ac43000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007fee1ac30000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fee1ac01000)
        liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fee1abdb000)
        libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007fee1ab1f000)
        libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007fee1aaf2000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fee1aa21000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fee1a8da000)
        libxxhash.so.0 => /lib/x86_64-linux-gnu/libxxhash.so.0 (0x00007fee1a8c5000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fee1a7e6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fee1b2c0000)
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007fee1a7da000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fee1a7b0000)
```

As you may notice, this affects to every `apt`-related executable. This happen only in gcc:9 and gcc:10

Tested with amd64 image, but it may happen with the rest of the architectures.

**Comment by yosifkit** [comment] 2023-06-23 17:13
Duplicate of #93. Fixed by #94. Still pending a Docker Official Images build: [See a change merged here that doesn't show up on Docker Hub yet?
](https://github.com/docker-library/gcc/tree/5986ef2ca54a29b5429a7a355a9c5e9826b88964#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet)

**Closed by yosifkit** 2023-06-23 17:13 UTC
